services:
    kassner.auth.controller_listener:
        class: Kassner\AuthBundle\Security\ControllerListener
        arguments: [ @annotation_reader, @security.context ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    kassner.auth.voter:
        class: Kassner\AuthBundle\Security\Voter
        public: false
        tags:
            - { name: security.voter }

    auth.user:
        class: Kassner\AuthBundle\Service\User
        arguments: [ @doctrine.orm.default_entity_manager ]

    auth.group:
        class: Kassner\AuthBundle\Service\Group
        arguments: [ @doctrine.orm.default_entity_manager ]
